const MARKET_GAMES = [
  { id: 'pokemon', name: '宝可梦 TCG', icon: 'fa-star', offers: '3.2k', color: '#FFCB05' },
  { id: 'honor', name: '王者荣耀', icon: 'fa-shield', offers: '12.4k', color: '#c41e3a' },
  { id: 'genshin', name: '原神', icon: 'fa-star-o', offers: '8.2k', color: '#4fc3f7' },
  { id: 'pubg', name: '和平精英', icon: 'fa-crosshairs', offers: '6.1k', color: '#ff9800' },
  { id: 'lol', name: '英雄联盟', icon: 'fa-bolt', offers: '9.8k', color: '#c89b3c' },
  { id: 'cs2', name: 'CS2', icon: 'fa-bullseye', offers: '15.2k', color: '#f97316' },
  { id: 'dnf', name: 'DNF', icon: 'fa-fire', offers: '4.3k', color: '#e91e63' },
  { id: 'wow', name: '魔兽世界', icon: 'fa-globe', offers: '11.1k', color: '#ffd700' },
  { id: 'valorant', name: 'Valorant', icon: 'fa-gamepad', offers: '5.6k', color: '#ff4655' },
];

const MARKET_PRODUCTS = [
  {
    id: 'p007',
    game: 'pokemon',
    gameName: '宝可梦 TCG',
    type: 'cards',
    typeLabel: '评级卡牌',
    title: '皮卡丘 VMAX · 简体中文 · PSA 10',
    price: 12800,
    server: 'SV 系列 · 2024',
    level: 'PSA 10',
    seller: '卡牌Vault',
    sellerRating: 5.0,
    sellerOrders: 892,
    delivery: '顺丰保价',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: true,
    legacyPlan: '收藏家版',
    tags: ['PSA评级', '保真验卡', '安心计划'],
    image: '⚡',
    cardGrade: 'PSA 10',
    cardSet: 'Simplified Chinese SV',
    items: ['PSA 10 全品', '官网可查编号', '防潮密封运输', '开箱录像留档'],
    linkedAssets: ['购入凭证 · 平台存证', '关联安心计划档案'],
    verifyNote: 'PSA 官网验真 · 2026-08-20',
  },
  {
    id: 'p008',
    game: 'pokemon',
    gameName: '宝可梦 TCG',
    type: 'cards',
    typeLabel: '未拆封盒',
    title: '151 收藏增强盒 · 日版 · 原箱未拆',
    price: 2680,
    server: 'Scarlet & Violet 151',
    level: '原箱',
    seller: '云伴认证卖家',
    sellerRating: 4.9,
    sellerOrders: 456,
    delivery: '48小时内',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: false,
    tags: ['原箱未拆', '溯源码', '110%包赔'],
    image: '📦',
    items: ['日版原箱', '防伪溯源贴', '平台验封', '全程录像'],
    linkedAssets: [],
    verifyNote: '封条验真 · 2026-08-22',
  },
  {
    id: 'p009',
    game: 'pokemon',
    gameName: '宝可梦周边',
    type: 'toys',
    typeLabel: '实体玩偶',
    title: '耿鬼 plush · 官方正版 · 30cm 限定',
    price: 399,
    server: 'Pokemon Center 日版',
    level: '全新',
    seller: 'ToyHunter',
    sellerRating: 4.8,
    sellerOrders: 1203,
    delivery: '3-5 天',
    verified: true,
    escrow: true,
    compensation: false,
    legacy: true,
    legacyPlan: '玩家入门版',
    tags: ['正版授权', '吊牌齐全'],
    image: '👻',
    items: ['官方吊牌', '原包装', '购买小票复印件', '平台品相报告'],
    linkedAssets: ['安心计划 · 收藏品登记'],
    verifyNote: '吊牌防伪 · 2026-08-18',
  },
  {
    id: 'p010',
    game: 'pokemon',
    gameName: '宝可梦 TCG',
    type: 'cards',
    typeLabel: '高罕卡牌',
    title: '喷火龙 ex SAR · 日版 · BGS 9.5',
    price: 45600,
    server: 'Pokemon 151',
    level: 'BGS 9.5',
    seller: 'LegacyGuard',
    sellerRating: 4.9,
    sellerOrders: 234,
    delivery: '专人护送',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: true,
    legacyPlan: '硬核玩家版',
    tags: ['BGS评级', '高值托管', '安心计划'],
    image: '🔥',
    cardGrade: 'BGS 9.5',
    cardSet: 'Japanese 151',
    items: ['BGS 9.5 金标', '中心ing 完美', '保险级包装', '高值专属验卡报告'],
    linkedAssets: ['香港保险加保可选', '区块链存证'],
    verifyNote: 'BGS 官网 + 显微镜验卡 · 2026-08-23',
  },
  {
    id: 'p001',
    game: 'honor',
    gameName: '王者荣耀',
    type: 'account',
    typeLabel: '成品账号',
    title: 'V10 全皮肤 · 荣耀典藏3件 · 星元200+',
    price: 2888,
    server: '微信区 · 王者50星',
    level: 'V10',
    seller: '云伴认证卖家',
    sellerRating: 4.9,
    sellerOrders: 1286,
    delivery: '30分钟内',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: true,
    legacyPlan: '硬核玩家版',
    tags: ['官方验号', '110%包赔', '安心计划'],
    image: '🎮',
    items: ['典藏皮肤：全息碎影', '典藏皮肤：无限飓风号', '传说皮肤×47', '星元部件200+'],
    linkedAssets: ['微信绑定 · 已实名', '关联素材包：HUD皮肤×12'],
    verifyNote: '登录验号录屏 · 2026-08-20',
  },
  {
    id: 'p002',
    game: 'genshin',
    gameName: '原神',
    type: 'account',
    typeLabel: '成品账号',
    title: '60级 · 五星角色18 · 精5武器8 · 深渊满星',
    price: 4200,
    server: '官服 · 天空岛',
    level: 'AR60',
    seller: 'LegacyGuard',
    sellerRating: 4.8,
    sellerOrders: 892,
    delivery: '1小时内',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: true,
    legacyPlan: '游戏达人版',
    tags: ['官方验号', '找回包赔'],
    image: '⚔️',
    items: ['满命：夜兰、胡桃', '精5：若水、护摩', '五星×18', '满探索度'],
    linkedAssets: ['米哈游通行证', '关联 MOD 资源包×3'],
    verifyNote: '官方 API 验号 · 2026-08-22',
  },
  {
    id: 'p003',
    game: 'cs2',
    gameName: 'CS2',
    type: 'items',
    typeLabel: '饰品库存',
    title: '蝴蝶刀 渐变大理石 FN · 库存47件',
    price: 8600,
    server: 'Steam · 国服',
    level: 'Prime',
    seller: 'SkinVault',
    sellerRating: 5.0,
    sellerOrders: 2341,
    delivery: '即时交付',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: false,
    tags: ['Steam验号', '资金托管'],
    image: '🔪',
    items: ['蝴蝶刀 渐变大理石 FN', 'AK-47 火蛇 MW', 'AWP 巨龙传说 FT', '合计47件'],
    linkedAssets: ['Steam 账号 · 7年账龄'],
    verifyNote: 'Steam 库存截图 · 2026-08-23',
  },
  {
    id: 'p011',
    game: 'pokemon',
    gameName: '宝可梦周边',
    type: 'toys',
    typeLabel: '拼装模型',
    title: '宝可梦拼装模型套装 · 皮卡丘+伊布 · 未拆',
    price: 268,
    server: '万代正版',
    level: '全新',
    seller: 'ToyHunter',
    sellerRating: 4.7,
    sellerOrders: 678,
    delivery: '2-4 天',
    verified: true,
    escrow: true,
    compensation: false,
    legacy: false,
    tags: ['正版', '未拆'],
    image: '🧩',
    items: ['万代防伪', '板件完整', '说明书齐全'],
    linkedAssets: [],
    verifyNote: '包装验真 · 2026-08-19',
  },
  {
    id: 'p004',
    game: 'pubg',
    gameName: '和平精英',
    type: 'account',
    typeLabel: '成品账号',
    title: '无敌战神 · 红装3套 · 载具皮肤全',
    price: 1580,
    server: 'QQ区',
    level: '战神',
    seller: '云伴认证卖家',
    sellerRating: 4.7,
    sellerOrders: 567,
    delivery: '20分钟内',
    verified: true,
    escrow: true,
    compensation: false,
    legacy: true,
    legacyPlan: '玩家入门版',
    tags: ['验号录屏'],
    image: '🎯',
    items: ['红装：梦幻火箭', '载具皮肤×15', '枪皮200+'],
    linkedAssets: [],
    verifyNote: '录屏验号 · 2026-08-21',
  },
  {
    id: 'p005',
    game: 'lol',
    gameName: '英雄联盟',
    type: 'account',
    typeLabel: '成品账号',
    title: '全英雄 · 皮肤520+ · 至臻×12',
    price: 3200,
    server: '艾欧尼亚',
    level: '钻石I',
    seller: 'ProTrader',
    sellerRating: 4.6,
    sellerOrders: 423,
    delivery: '1小时内',
    verified: true,
    escrow: true,
    compensation: true,
    legacy: false,
    tags: ['验号', '托管'],
    image: '🏆',
    items: ['至臻皮肤×12', '限定皮肤×38', '全英雄'],
    linkedAssets: ['QQ绑定'],
    verifyNote: '客户端验号 · 2026-08-19',
  },
  {
    id: 'p006',
    game: 'genshin',
    gameName: '原神',
    type: 'items',
    typeLabel: '游戏素材包',
    title: 'Unity UI Kit · 游戏HUD素材 · 商用授权',
    price: 299,
    server: '数字资产',
    level: '—',
    seller: 'DevAssets',
    sellerRating: 4.9,
    sellerOrders: 156,
    delivery: '即时下载',
    verified: true,
    escrow: true,
    compensation: false,
    legacy: true,
    legacyPlan: '开发者版',
    tags: ['版权存证', '素材关联'],
    image: '🎨',
    items: ['UI 组件 120+', '图标 800+', 'Unity UGUI', '商用授权链上存证'],
    linkedAssets: ['关联 Steam 开发者账号', 'Git 仓库托管'],
    verifyNote: '版权哈希上链 · 2026-08-15',
  },
];

function getProduct(id) {
  return MARKET_PRODUCTS.find(p => p.id === id);
}

function filterProducts(filters = {}) {
  return MARKET_PRODUCTS.filter(p => {
    if (filters.game && filters.game !== 'all' && p.game !== filters.game) return false;
    if (filters.type && filters.type !== 'all' && p.type !== filters.type) return false;
    if (filters.legacy === 'yes' && !p.legacy) return false;
    if (filters.minPrice && p.price < Number(filters.minPrice)) return false;
    if (filters.maxPrice && p.price > Number(filters.maxPrice)) return false;
    if (filters.q) {
      const q = filters.q.toLowerCase();
      if (!p.title.toLowerCase().includes(q) && !p.gameName.includes(filters.q)) return false;
    }
    return true;
  });
}
